sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

addons:
  apt:
    packages:
      - build-essential
      - libudev-dev

before_install:
  - pkg-config --list-all
  - pkg-config --libs libudev
  - pkg-config --modversion libudev