[package]
name = "u2fhid"
version = "0.1.0"
authors = ["Kyle Machulis <kyle@nonpolynomial.com>"]

[target.x86_64-unknown-linux-gnu.dependencies]
nix = "^0.7"
libudev = "^0.2"
libc = "^0.2"
clap = {version = "2", features = ["yaml"]}
