[package]
name = "u2fhid"
version = "0.1.0"
authors = ["Kyle Machulis <kyle@nonpolynomial.com>", "J.C. Jones <jc@mozilla.org>", "Tim Taubert <ttaubert@mozilla.com>"]
build = "build.rs"

[target.'cfg(unix)'.dependencies]
nix = "^0.7"
libc = "^0.2"
clap = {version = "2", features = ["yaml"]}
rust-crypto = "^0.2"
base64 = "^0.4"

[target.'cfg(target_os = "linux")'.dependencies]
libudev = "^0.2"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation-sys = "0.3.1"
mach = "0.0.5"

[dependencies]
rand = "0.3"
log = "0.3"
env_logger = "0.3"
